name: local_config
description: "A new Flutter package project."
version: 0.0.1
homepage:

environment:
  sdk: ^3.9.0
  flutter: ">=1.17.0"

flutter:
  generate: true

dependencies:
  flutter:
    sdk: flutter
  shared_preferences: ^2.5.3
  re_editor: ^0.7.0
  re_highlight: ^0.0.3
  get_it: ^8.2.0
  provider: ^6.1.5+1
  flutter_localizations:
    sdk: flutter
  intl: ^0.20.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
