name: local_config
description: "A new Flutter package project."
version: 0.0.1
homepage:

environment:
  sdk: ">=3.4.3 <4.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  firebase_analytics: ^11.5.0
  firebase_remote_config: ^5.4.5
  shared_preferences: ^2.5.3
  re_editor: ^0.7.0
  re_highlight: ^0.0.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
