name: local_config_sample
description: "A sample demonstrating the usage of the local_config package"
publish_to: "none"

environment:
  sdk: ">=3.4.3 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  local_config:
    path: ..
  firebase_core: ^3.14.0
  firebase_analytics: ^11.5.0
  firebase_remote_config: ^5.4.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
